# =============
# DEVELOPMENT
# =============
OTHER_TECH = [
    "Docker",
    "Rkt",
    "LXC",
    "Vagrant",
    "Elasticsearch",
    "Nginx",
    "Git",
    "Jira",
    "REST",
    "Apache Hadoop",
    "Scrum",
    "Redmine",
    "Mercurial",
    "Apache Kafka",
    "Apache Spark"
]

LICENSES = [
    "Apache License, 2.0 (Apache-2.0)",
    "The BSD 3-Clause License",
    "The BSD 2-Clause License",
    "GNU General Public License (GPL)",
    "General Public License (LGPL)",
    "MIT License (MIT)",
    "Mozilla Public License 2.0 (MPL-2.0)",
    "Common Development and Distribution License (CDDL-1.0)",
    "Eclipse Public License (EPL-1.0)"
]

PROGRAMMING_LANGS = [
    "ASP",
    "Assembly",
    "AutoIt",
    "Awk",
    "Bash",
    "C",
    "C Shell",
    "C#",
    "C++",
    "Caml",
    "Ceylon",
    "Clojure",
    "CoffeeScript",
    "Common Lisp",
    "D",
    "Dart",
    "Delphi",
    "Dylan",
    "ECMAScript",
    "Elixir",
    "Emacs Lisp",
    "Erlang",
    "F#",
    "Falcon",
    "Fortran",
    "GNU Octave",
    "Go",
    "Groovy",
    "Haskell",
    "haXe",
    "Io",
    "J#",
    "Java",
    "JavaScript",
    "Julia",
    "Kotlin",
    "Lisp",
    "Lua",
    "Mathematica",
    "Objective-C",
    "OCaml",
    "Perl",
    "PHP",
    "PL-I",
    "PL-SQL",
    "PowerShell",
    "Prolog",
    "Python",
    "R",
    "Racket",
    "Ruby",
    "Rust",
    "Scala",
    "Scheme",
    "Smalltalk",
    "Tcl",
    "Tex",
    "Transact-SQL",
    "TypeScript",
    "Z shell"
]

NOSQL = (
    "Aerospike",
    "Aerospike",
    "AllegroGraph",
    "Apache Cassandra",
    "CouchDB",
    "Couchbase",
    "Hyperdex",
    "InfiniteGraph",
    "MUMPS",
    "MemcacheDB",
    "Memcached",
    "MongoDB",
    "Neo4J",
    "Redis",
    "RethinkDB",
    "Riak"
)

SQL = (
    "MariaDB",
    "MySQL",
    "PostgreSQL",
    "Oracle DB",
    "SQLite"
    "DB2"
)

BACKEND = [
    "C#",
    "C#/ASP.NET",
    "Java",
    "Java/Tapestry",
    "Go/Beego",
    "Python",
    "Python/Bottle",
    "Python/CherryPy",
    "Erlang",
    "Erlang/ChicagoBoss",
    "Erlang/Cowboy",
    "Clojure",
    "Django",
    "Python/Django",
    "Python/Flask/Gunicorn",
    "Elixir",
    "Elixir/Phoenix",
    "Elixir/Erlang",
    "Node.JS",
    "Node/Express",
    "Falcon",
    "Falcon/Python",
    "Flask",
    "Python/Flask",
    "Go/Gin",
    "Go/Martini",
    "Go",
    "Go/Gorilla",
    "Groovy/Grails",
    "Java",
    "PHP/Laravel",
    "PHP",
    "Lua",
    "Java/Ninja",
    "PHP/Symfony",
    "PHP/Yii 2",
    "Pyramid",
    "Python/Pyramid",
    "Python/Flask/SQLAlchemy",
    "Python/SQLAlchemy",
    "Python/Twisted",
    "Python/web2py",
    "Go/Revel",
    "Ruby",
    "Ruby on Rails",
    "Ruby/Sinatra",
    "Java/Spring",
    "PHP/Symfony",
    "Python/Tornado",
    "Werkzeug",
    "Python/Werkzeug",
    "PHP/Zend Framework"
]

FRONTEND = [
    "JavaScript/Angular 2",
    "JavaScript/Backbone",
    "Gulp/Bower/Sass",
    "JS/HTML/CSS/Canvas/SVG",
    "JavaScript/Ember",
    "JavaScript/React",
    "JavaScript/React/Redux",
    "JavaScript/React/Redux/Flux",
    "JS/HTML/CSS",
    "JavaScript/Highcharts.js",
    "JS/Twitter Bootstrap",
    "React/Canvas/SVG",
    "React/D3.js",
    'React/Redux/Babel',
    "JavaScript/Reflux/Redux",
    "JS/Sass/Less/Gulp",
    "Stylus/Sass/Webpack",
    "JavaScript/Vue",
    "JavaScript/jQuery",
    "TypeScript/React",
    "TypeScript/CSS/HTML",
    'Webpack/Grunt/PostCSS'
]

OS = [
    "Arch",
    "CentOS",
    "Debian",
    "Fedora",
    "FreeBSD",
    "Gentoo",
    "Kali",
    "Lubuntu",
    "Manjaro",
    "Mint",
    "OS X",
    "OpenBSD",
    "PCLinuxOS",
    "Slackware",
    "Ubuntu",
    "Windows 10",
    "Windows 7",
    "Windows 8",
    "Windows 8.1",
    "Zorin",
    "elementaryOS",
    "macOS",
    "openSUSE"
]
