User's Guide
------------

This part of the documentation begins with some background information about
Mimesis then focuses on step-by-step instructions for using Mimesis.

.. toctree::
   :maxdepth: 2

   foreword
   installation
   quickstart
   advanced


API Reference
-------------

If you are looking for information on a specific function, class or
method, this part of the documentation is for you.

.. toctree::
   :maxdepth: 3

   api


Contributing
------------

Your contributions are always welcome! Please adhere to the contribution guidelines:

1. Take a look at `contributing guidelines <https://github.com/lk-geimfari/mimesis/blob/master/CONTRIBUTING.md>`_.
2. Check for open issues or open a fresh issue to start a discussion around a feature idea or a bug.
3. Fork the repository on GitHub to start making your changes to the *your_branch* branch.
4. Add yourself to the list of `contributors <https://github.com/lk-geimfari/mimesis/blob/master/CONTRIBUTORS.md>`_.
5. Send a pull request and bug the maintainer until it gets merged and published.


Additional Notes
----------------

Disclaimer, legal information and other information are here for the interested.

.. toctree::
   :maxdepth: 1

   notes


Indices
-------

* :ref:`genindex`
* :ref:`modindex`
* :ref:`search`
