Contents
--------

Mimesis provides configuration and conventions, with sensible defaults. This section of the
documentation explains the different parts of the Mimesis and how they can be used, customized, and extended.

.. toctree::
   :maxdepth: 2

   about
   installation
   quickstart
   locales
   providers
   schema
   random_and_seed
   tips


API Reference
-------------

If you are looking for information on a specific function, class or
method, this part of the documentation is for you.

.. toctree::
   :maxdepth: 2

   api
   glossary


Additional Information
----------------------

Disclaimer, legal information and other information are here for the interested.

.. toctree::
   :maxdepth: 1

   additional-info
   contributing


Changelog
---------

Here you can see the full list of changes between each Mimesis release.

.. toctree::
   :maxdepth: 1

   changelog


Indices
-------

* :ref:`genindex`
* :ref:`search`
